# Generated by Django 5.1.4 on 2025-12-30 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filiere', models.CharField(choices=[('mathematiques', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('informatique', 'Informatique'), ('genie_civil', 'Génie Civil'), ('electronique', 'Électronique'), ('mecanique', 'Mécanique'), ('biologie', 'Biologie')], max_length=50)),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('session', models.CharField(choices=[('premiere', 'Première session'), ('deuxieme', 'Deuxième session'), ('rattrapage', 'Session de rattrapage')], max_length=50)),
                ('type', models.CharField(choices=[('composition', 'Composition'), ('ds', 'Devoir Surveillé'), ('tp', 'Travaux Pratiques'), ('td', 'Travaux Dirigés')], default='composition', max_length=50)),
                ('fichier', models.FileField(upload_to='epreuves/%Y/', verbose_name='Fichier PDF')),
                ('taille', models.CharField(blank=True, max_length=20, verbose_name='Taille')),
                ('nombre_telechargements', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epreuves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Épreuve',
                'verbose_name_plural': 'Épreuves',
                'db_table': 'epreuves',
                'ordering': ['-annee', 'filiere', 'session'],
                'indexes': [models.Index(fields=['filiere', 'annee'], name='epreuves_filiere_b79f66_idx'), models.Index(fields=['is_published'], name='epreuves_is_publ_ae6d62_idx')],
            },
        ),
    ]
