# Generated by Django 5.1.4 on 2025-12-30 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_epreuve'),
        ('configurations', '0006_departement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epreuve',
            options={'ordering': ['-annee', 'filiere'], 'verbose_name': 'Épreuve', 'verbose_name_plural': 'Épreuves'},
        ),
        migrations.RenameIndex(
            model_name='epreuve',
            new_name='epreuves_filiere_523b58_idx',
            old_name='epreuves_filiere_b79f66_idx',
        ),
        migrations.RemoveField(
            model_name='epreuve',
            name='session',
        ),
        migrations.RemoveField(
            model_name='epreuve',
            name='type',
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epreuves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='fichier',
            field=models.FileField(upload_to='epreuves/%Y/%m/%d/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='configurations.filiere'),
        ),
    ]
