# Generated by Django 5.1.4 on 2025-12-27 10:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidats', '0001_initial'),
        ('configurations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, help_text='A, C, D, etc.', max_length=100, null=True)),
                ('annee_obtention_diplome', models.IntegerField(blank=True, null=True)),
                ('pays_obtention_diplome', models.CharField(blank=True, max_length=100, null=True)),
                ('etablissement_origine', models.CharField(blank=True, max_length=255, null=True)),
                ('ville_etablissement', models.CharField(blank=True, max_length=100, null=True)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mention', models.CharField(blank=True, choices=[('Passable', 'Passable'), ('AB', 'Assez Bien'), ('B', 'Bien'), ('TB', 'Très Bien')], max_length=50, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('en_attente', 'En Attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=20)),
                ('numero_inscription', models.CharField(blank=True, help_text="Numéro d'inscription généré", max_length=50, null=True, unique=True)),
                ('qr_code_path', models.CharField(blank=True, help_text='Chemin du QR code', max_length=255, null=True)),
                ('fiche_inscription_path', models.CharField(blank=True, help_text='Chemin de la fiche PDF', max_length=255, null=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='configurations.anneescolaire')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='candidats.candidat')),
                ('centre_depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='configurations.centredepot')),
                ('centre_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='configurations.centreexamen')),
                ('diplome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='configurations.diplome')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='candidats.dossier')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='configurations.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='configurations.niveau')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'inscription',
                'indexes': [models.Index(fields=['candidat'], name='inscription_candida_ebdd83_idx'), models.Index(fields=['statut'], name='inscription_statut_6d5bac_idx'), models.Index(fields=['numero_inscription'], name='inscription_numero__3c3eb9_idx'), models.Index(fields=['filiere'], name='inscription_filiere_b9c2d0_idx'), models.Index(fields=['niveau'], name='inscription_niveau__f94464_idx')],
            },
        ),
    ]
