# Generated by Django 5.1.4 on 2025-12-28 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQuitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='Code Quitus')),
                ('montant', models.DecimalField(decimal_places=2, default=50000, max_digits=10, verbose_name='Montant (FCFA)')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('date_utilisation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
                ('reference_bancaire', models.CharField(max_length=50, unique=True, verbose_name='Référence bancaire')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_quitus', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code Quitus',
                'verbose_name_plural': 'Codes Quitus',
                'db_table': 'codes_quitus',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='TransactionBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_payeur', models.CharField(max_length=200, verbose_name='Nom du payeur')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('date_paiement', models.DateTimeField(verbose_name='Date de paiement')),
                ('banque', models.CharField(max_length=100, verbose_name='Banque')),
                ('agence', models.CharField(max_length=100, verbose_name='Agence')),
                ('numero_recu', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_quitus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='authentication.codequitus', verbose_name='Code Quitus')),
            ],
            options={
                'verbose_name': 'Transaction Bancaire',
                'verbose_name_plural': 'Transactions Bancaires',
                'db_table': 'transactions_bancaires',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.AddIndex(
            model_name='codequitus',
            index=models.Index(fields=['code', 'utilise'], name='codes_quitu_code_db30c8_idx'),
        ),
        migrations.AddIndex(
            model_name='codequitus',
            index=models.Index(fields=['date_expiration'], name='codes_quitu_date_ex_a69815_idx'),
        ),
    ]
