# Generated by Django 5.1.4 on 2025-12-30 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_codequitus_transactionbancaire_and_more'),
        ('configurations', '0006_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin_academique', 'Administrateur Académique'), ('responsable_filiere', 'Responsable de Filière'), ('candidat', 'Candidat')], default='candidat', max_length=30),
        ),
        migrations.CreateModel(
            name='ResponsableFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables', to='configurations.filiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_filiere_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable de Filière',
                'verbose_name_plural': 'Responsables de Filière',
                'db_table': 'responsables_filiere',
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_user', 'Création utilisateur'), ('update_user', 'Modification utilisateur'), ('delete_user', 'Suppression utilisateur'), ('reset_password', 'Réinitialisation mot de passe'), ('toggle_active', 'Activation/Désactivation compte'), ('assign_role', 'Attribution rôle')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_received', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur cible')),
            ],
            options={
                'verbose_name': 'Log Action Utilisateur',
                'verbose_name_plural': 'Logs Actions Utilisateurs',
                'db_table': 'user_action_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
