# Generated by Django 5.1.4 on 2025-12-27 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex: 2024-2025', max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_debut_inscription', models.DateField(blank=True, null=True)),
                ('date_fin_inscription', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Une seule année active à la fois')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Année Scolaire',
                'verbose_name_plural': 'Années Scolaires',
                'db_table': 'annee_scolaire',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CentreDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=191, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('horaires', models.TextField(blank=True, help_text="Horaires d'ouverture", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centre de Dépôt',
                'verbose_name_plural': 'Centres de Dépôt',
                'db_table': 'centre_depot',
            },
        ),
        migrations.CreateModel(
            name='CentreExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('capacite', models.IntegerField(default=0, help_text='Nombre de places')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=191, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Centre d'Examen",
                'verbose_name_plural': "Centres d'Examen",
                'db_table': 'centre_examen',
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: BAC, LICENCE', max_length=50, unique=True)),
                ('libelle', models.CharField(help_text='Ex: Baccalauréat', max_length=255)),
                ('niveau_etude', models.CharField(blank=True, help_text='Secondaire, Supérieur', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diplôme',
                'verbose_name_plural': 'Diplômes',
                'db_table': 'diplome',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: INF, GC, GM', max_length=20, unique=True)),
                ('libelle', models.CharField(help_text='Ex: Informatique', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_annees', models.IntegerField(default=3, help_text='Durée en années')),
                ('frais_inscription', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'db_table': 'filiere',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: L1, L3', max_length=20, unique=True)),
                ('libelle', models.CharField(help_text='Ex: Première Année', max_length=100)),
                ('ordre', models.IntegerField(help_text='1, 3, etc.', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'db_table': 'niveau',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='FiliereNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_disponibles', models.IntegerField(default=0)),
                ('places_occupees', models.IntegerField(default=0)),
                ('frais_scolarite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_niveaux', to='configurations.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_niveaux', to='configurations.niveau')),
            ],
            options={
                'verbose_name': 'Filière-Niveau',
                'verbose_name_plural': 'Filières-Niveaux',
                'db_table': 'filiere_niveau',
                'unique_together': {('filiere', 'niveau')},
            },
        ),
        migrations.CreateModel(
            name='FiliereDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='Diplôme obligatoire ou optionnel')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='configurations.diplome')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes_requis', to='configurations.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes_requis', to='configurations.niveau')),
            ],
            options={
                'verbose_name': 'Filière-Diplôme',
                'verbose_name_plural': 'Filières-Diplômes',
                'db_table': 'filiere_diplome',
                'unique_together': {('filiere', 'niveau', 'diplome')},
            },
        ),
    ]
