# Generated by Django 5.1.4 on 2025-12-27 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: A4, C, D', max_length=20, unique=True)),
                ('libelle', models.CharField(help_text='Ex: Baccalauréat A4', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: TB, B, AB', max_length=20, unique=True)),
                ('libelle', models.CharField(help_text='Très Bien, Bien, Assez Bien', max_length=100)),
                ('minimum_points', models.DecimalField(decimal_places=2, help_text='Points minimum GCE', max_digits=5)),
                ('maximum_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: A1, A2, C1', max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='configurations.bac')),
            ],
        ),
        migrations.CreateModel(
            name='SerieFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='configurations.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_filieres', to='configurations.niveau')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='configurations.serie')),
            ],
            options={
                'unique_together': {('serie', 'filiere', 'niveau')},
            },
        ),
    ]
