# Generated by Django 5.1.4 on 2025-12-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_bac_mention_serie_seriefiliere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mention',
            options={'ordering': ['-maximum_points'], 'verbose_name': 'Mention', 'verbose_name_plural': 'Mentions'},
        ),
        migrations.AddField(
            model_name='mention',
            name='bac',
            field=models.ForeignKey(default=1, help_text='Type de BAC concerné', on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='configurations.bac'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mention',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mention',
            name='code',
            field=models.CharField(help_text='Ex: TB, B, AB, PASSABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='mention',
            name='libelle',
            field=models.CharField(help_text='Ex: Très Bien, Bien, Assez Bien', max_length=100),
        ),
        migrations.AlterField(
            model_name='mention',
            name='maximum_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Points maximum GCE (ex: 18)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mention',
            name='minimum_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Points minimum GCE (ex: 15)', max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mention',
            unique_together={('bac', 'code')},
        ),
        migrations.AlterModelTable(
            name='mention',
            table='mention',
        ),
    ]
