# Generated by Django 5.1.4 on 2025-12-28 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_alter_mention_options_mention_bac_mention_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mention',
            options={'ordering': ['bac', 'minimum_points'], 'verbose_name': 'Mention', 'verbose_name_plural': 'Mentions'},
        ),
        migrations.AlterField(
            model_name='mention',
            name='bac',
            field=models.ForeignKey(help_text='BAC auquel appartient cette mention', on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='configurations.bac'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='maximum_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Points maximum (ex: 11.99 pour Passable)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mention',
            name='minimum_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Points minimum (ex: 10.00 pour Passable)', max_digits=5, null=True),
        ),
    ]
