# Generated by Django 5.1.4 on 2026-01-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='quota',
            field=models.IntegerField(default=300, help_text='Nombre de places disponibles'),
        ),
    ]
