# Generated by Django 5.1.4 on 2026-01-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_filiere_quota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['code'], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AddField(
            model_name='filiere',
            name='campus',
            field=models.CharField(blank=True, help_text='Campus où se déroule la formation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='competences',
            field=models.TextField(blank=True, help_text='Compétences acquises (séparées par des points-virgules)', null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='debouches',
            field=models.TextField(blank=True, help_text='Débouchés professionnels (séparés par des points-virgules)', null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='diplome_delivre',
            field=models.CharField(default='Licence', help_text='Diplôme délivré à la fin', max_length=100),
        ),
        migrations.AddField(
            model_name='filiere',
            name='frais_scolarite',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Frais de scolarité annuels en FCFA', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='horaires',
            field=models.CharField(default='Lundi-Vendredi 8h-17h', help_text='Horaires des cours', max_length=100),
        ),
        migrations.AddField(
            model_name='filiere',
            name='moyenne_minimale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne minimale requise sur 20', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='niveau_entree',
            field=models.CharField(default='Baccalauréat', help_text="Niveau requis pour l'admission", max_length=50),
        ),
        migrations.AddField(
            model_name='filiere',
            name='series_acceptees',
            field=models.CharField(blank=True, help_text='Séries acceptées (ex: C, D, E)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée de la filière', null=True),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='duree_annees',
            field=models.IntegerField(default=3, help_text='Durée de formation en années'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='frais_inscription',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Frais d'inscription annuels en FCFA", max_digits=10, null=True),
        ),
    ]
