# Generated by Django 5.1.4 on 2025-12-27 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, help_text='Généré automatiquement', max_length=50, null=True, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(default='Camerounaise', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=191)),
                ('nom_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_pere', models.CharField(blank=True, max_length=20, null=True)),
                ('profession_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_mere', models.CharField(blank=True, max_length=20, null=True)),
                ('profession_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_tuteur', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_tuteur', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_actuelle', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('boite_postale', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('statut_dossier', models.CharField(choices=[('incomplet', 'Incomplet'), ('complet', 'Complet'), ('en_attente', 'En Attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='incomplet', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'db_table': 'candidat',
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(blank=True, help_text='Numéro unique du dossier', max_length=50, null=True, unique=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En Cours'), ('complet', 'Complet'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('cloture', 'Clôturé')], default='ouvert', max_length=20)),
                ('date_ouverture', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, help_text='Remarques administratives', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='configurations.anneescolaire')),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='candidats.candidat')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'db_table': 'dossier',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('acte_naissance', 'Acte de Naissance'), ('diplome', 'Diplôme'), ('releve_notes', 'Relevé de Notes'), ('photo_identite', "Photo d'Identité"), ('certificat_nationalite', 'Certificat de Nationalité'), ('quitus_paiement', 'Quitus de Paiement'), ('certificat_inscription', "Certificat d'Inscription"), ('attestation_reussite', 'Attestation de Réussite'), ('autre', 'Autre')], max_length=50)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('nom_original', models.CharField(max_length=255)),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('taille_fichier', models.IntegerField(blank=True, help_text='Taille en octets', null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('commentaire_verification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidats.candidat')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verifies', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidats.dossier')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Quitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code à 6 chiffres', max_length=6, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banque', models.CharField(blank=True, help_text='Nom de la banque', max_length=100, null=True)),
                ('reference_paiement', models.CharField(blank=True, help_text='Référence bancaire', max_length=100, null=True)),
                ('date_paiement', models.DateField(blank=True, help_text='Date du paiement', null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quitus', to='configurations.anneescolaire')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quitus_utilise', to='candidats.candidat')),
            ],
            options={
                'verbose_name': 'Quitus',
                'verbose_name_plural': 'Quitus',
                'db_table': 'quitus',
            },
        ),
        migrations.AddField(
            model_name='candidat',
            name='quitus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidat', to='candidats.quitus'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['numero_dossier'], name='dossier_numero__4e168b_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['statut'], name='dossier_statut_d4d445_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type_document'], name='document_type_do_67bbdd_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_verified'], name='document_is_veri_69323b_idx'),
        ),
        migrations.AddIndex(
            model_name='quitus',
            index=models.Index(fields=['code'], name='quitus_code_b4e510_idx'),
        ),
        migrations.AddIndex(
            model_name='quitus',
            index=models.Index(fields=['is_used'], name='quitus_is_used_6aea97_idx'),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['matricule'], name='candidat_matricu_451fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['nom', 'prenom'], name='candidat_nom_2ff517_idx'),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['statut_dossier'], name='candidat_statut__944784_idx'),
        ),
    ]
