# Generated by Django 5.1.4 on 2025-12-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0001_initial'),
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inscriptions.inscription'),
        ),
    ]
