# Generated by Django 5.1.4 on 2025-12-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0002_document_inscription'),
        ('configurations', '0003_alter_mention_options_mention_bac_mention_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidat',
            name='candidat_matricu_451fb3_idx',
        ),
        migrations.RemoveIndex(
            model_name='candidat',
            name='candidat_nom_2ff517_idx',
        ),
        migrations.RemoveIndex(
            model_name='candidat',
            name='candidat_statut__944784_idx',
        ),
        migrations.RemoveIndex(
            model_name='quitus',
            name='quitus_code_b4e510_idx',
        ),
        migrations.RemoveIndex(
            model_name='quitus',
            name='quitus_is_used_6aea97_idx',
        ),
        migrations.AddField(
            model_name='candidat',
            name='annee_obtention_diplome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='bac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.bac'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='centre_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.centredepot'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='centre_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.centreexamen'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='cni_file',
            field=models.FileField(blank=True, null=True, upload_to='candidats/cni/%Y/'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='diplome_file',
            field=models.FileField(blank=True, null=True, upload_to='candidats/diplomes/%Y/'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='etablissement_origine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.filiere'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.mention'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='mention_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Points GCE', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.niveau'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidats/photos/%Y/'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.serie'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone_mere',
            field=models.CharField(blank=True, db_column='tel_mere', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone_pere',
            field=models.CharField(blank=True, db_column='tel_pere', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='banque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
