# Generated by Django 5.1.4 on 2025-12-28 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0003_remove_candidat_candidat_matricu_451fb3_idx_and_more'),
        ('configurations', '0004_alter_mention_options_alter_mention_bac_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='annee_obtention_diplome',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='bac',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='centre_depot',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='centre_examen',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='cni_file',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='diplome_file',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='etablissement_origine',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='mention_points',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='serie',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='matricule',
            field=models.CharField(blank=True, help_text='Généré automatiquement', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone_mere',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone_pere',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='banque',
            field=models.CharField(blank=True, help_text='Nom de la banque', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='code',
            field=models.CharField(help_text='Code à 6 chiffres', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='date_paiement',
            field=models.DateField(blank=True, help_text='Date du paiement', null=True),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='reference_paiement',
            field=models.CharField(blank=True, help_text='Référence bancaire', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['matricule'], name='candidat_matricu_451fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['nom', 'prenom'], name='candidat_nom_2ff517_idx'),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['statut_dossier'], name='candidat_statut__944784_idx'),
        ),
        migrations.AddIndex(
            model_name='quitus',
            index=models.Index(fields=['code'], name='quitus_code_b4e510_idx'),
        ),
        migrations.AddIndex(
            model_name='quitus',
            index=models.Index(fields=['is_used'], name='quitus_is_used_6aea97_idx'),
        ),
    ]
