# Generated by Django 5.1.4 on 2025-12-30 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_codequitus_transactionbancaire_and_more'),
        ('candidats', '0005_departement_region_candidat_quartier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='quitus',
        ),
        migrations.AddField(
            model_name='candidat',
            name='code_quitus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidat', to='authentication.codequitus'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
