# Generated by Django 5.1.4 on 2025-12-30 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0006_remove_candidat_quitus_candidat_code_quitus_and_more'),
        ('configurations', '0006_departement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='telephone_mere',
            new_name='tel_mere',
        ),
        migrations.RenameField(
            model_name='candidat',
            old_name='telephone_pere',
            new_name='tel_pere',
        ),
        migrations.AddField(
            model_name='candidat',
            name='annee_obtention_diplome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='bac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.bac'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='centre_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.centredepot'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='centre_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.centreexamen'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='etablissement_origine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.filiere'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.mention'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.niveau'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.serie'),
        ),
    ]
