# Generated by Django 5.1.4 on 2026-01-07 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_created_by_user_nom_user_prenom_alter_user_role_and_more'),
        ('candidats', '0008_candidat_date_rejet_candidat_date_validation_and_more'),
        ('configurations', '0008_alter_filiere_options_filiere_campus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_enrollment', models.CharField(blank=True, help_text='Ex: ENR2025-00001', max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('sexe', models.CharField(max_length=1)),
                ('telephone', models.CharField(max_length=20)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=191)),
                ('nom_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_pere', models.CharField(blank=True, max_length=20, null=True)),
                ('profession_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_mere', models.CharField(blank=True, max_length=20, null=True)),
                ('profession_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_tuteur', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_tuteur', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_actuelle', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('etablissement_origine', models.CharField(max_length=255)),
                ('annee_obtention_diplome', models.IntegerField()),
                ('photo_path', models.CharField(max_length=255)),
                ('cni_path', models.CharField(max_length=255)),
                ('diplome_path', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('en_cours_validation', 'En Cours de Validation'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='soumis', max_length=30)),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_soumission', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_rejet', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enrollment History',
                'verbose_name_plural': 'Enrollment Histories',
                'db_table': 'enrollment_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='candidat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidat', 'verbose_name_plural': 'Candidats'},
        ),
        migrations.RemoveIndex(
            model_name='candidat',
            name='candidat_nom_2ff517_idx',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='bac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.bac'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='centre_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.centredepot'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='centre_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.centreexamen'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='code_quitus',
            field=models.ForeignKey(blank=True, help_text='Code quitus utilisé lors du REGISTER', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidat', to='authentication.codequitus'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date de validation du dernier enrollment', null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidats.departement'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='email',
            field=models.EmailField(help_text='Copie de user.email au moment du register', max_length=191),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.filiere'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='matricule',
            field=models.CharField(blank=True, help_text='Généré automatiquement', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.mention'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.niveau'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidats.region'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.serie'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='statut_dossier',
            field=models.CharField(choices=[('non_enrolle', 'Non Enrollé'), ('en_attente', 'En Attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='non_enrolle', help_text='Statut actuel du candidat', max_length=20),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['email'], name='candidat_email_db3fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['user'], name='candidat_user_id_4fa525_idx'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='bac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.bac'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='candidats.candidat'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='centre_depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.centredepot'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='centre_examen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.centreexamen'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='code_quitus_utilise',
            field=models.ForeignKey(blank=True, help_text='Code quitus vérifié lors de cet enrollment (doit être le même que candidat.code_quitus)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.codequitus'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidats.departement'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.filiere'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.mention'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.niveau'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidats.region'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='rejete_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_rejetes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.serie'),
        ),
        migrations.AddField(
            model_name='enrollmenthistory',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enrollmenthistory',
            index=models.Index(fields=['candidat', '-created_at'], name='enrollment__candida_f69968_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmenthistory',
            index=models.Index(fields=['statut'], name='enrollment__statut_dded37_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmenthistory',
            index=models.Index(fields=['numero_enrollment'], name='enrollment__numero__f39578_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmenthistory',
            index=models.Index(fields=['code_quitus_utilise'], name='enrollment__code_qu_4bc066_idx'),
        ),
    ]
