# Generated by Django 5.1.4 on 2026-01-11 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_created_by_user_nom_user_prenom_alter_user_role_and_more'),
        ('candidats', '0009_enrollmenthistory_alter_candidat_options_and_more'),
        ('configurations', '0008_alter_filiere_options_filiere_campus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('success', 'Succès'), ('validation', 'Validation'), ('error', 'Erreur'), ('rejection', 'Rejet'), ('warning', 'Avertissement'), ('info', 'Information')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='bac',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='centre_depot',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='centre_examen',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='code_quitus_utilise',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='region',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='rejete_par',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='enrollmenthistory',
            name='valide_par',
        ),
        migrations.AlterModelOptions(
            name='candidat',
            options={'verbose_name': 'Candidat', 'verbose_name_plural': 'Candidats'},
        ),
        migrations.RemoveIndex(
            model_name='candidat',
            name='candidat_email_db3fdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='candidat',
            name='candidat_user_id_4fa525_idx',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='bac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.bac'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='centre_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.centredepot'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='centre_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.centreexamen'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='code_quitus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidat', to='authentication.codequitus'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_naissance',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='candidats.departement'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='email',
            field=models.EmailField(max_length=191),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.filiere'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='lieu_naissance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.mention'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.niveau'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='candidats.region'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='configurations.serie'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='statut_dossier',
            field=models.CharField(choices=[('incomplet', 'Incomplet'), ('complet', 'Complet'), ('en_attente', 'En Attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='incomplet', max_length=20),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['nom', 'prenom'], name='candidat_nom_2ff517_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='candidats.candidat'),
        ),
        migrations.DeleteModel(
            name='EnrollmentHistory',
        ),
    ]
